// Reads src/data/<entity>/*.json (one file per entry) and writes
// src/lib/generated/<entity>.generated.ts — a plain array export built from
// individual JSON imports. Run automatically via predev/prebuild/prelint
// (see package.json); never edit the generated output by hand.
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const dataDir = path.join(rootDir, "src", "data");
const generatedDir = path.join(rootDir, "src", "lib", "generated");

// folder name under src/data -> { typeName, exportName, outFile }
const ENTITIES = [
  { folder: "producers", typeName: "Producer", exportName: "producers", outFile: "producers.generated.ts" },
  { folder: "articles", typeName: "Article", exportName: "articles", outFile: "articles.generated.ts" },
  { folder: "news", typeName: "NewsItem", exportName: "newsItems", outFile: "news-items.generated.ts" },
  { folder: "research", typeName: "ResearchPaper", exportName: "researchPapers", outFile: "research-papers.generated.ts" },
  { folder: "case-studies", typeName: "CaseStudy", exportName: "caseStudies", outFile: "case-studies.generated.ts" },
  { folder: "download-resources", typeName: "DownloadResource", exportName: "downloadResources", outFile: "download-resources.generated.ts" },
  { folder: "faq-items", typeName: "FaqItem", exportName: "faqItems", outFile: "faq-items.generated.ts" },
  { folder: "calculator-rates", typeName: "CalculatorRate", exportName: "calculatorRates", outFile: "calculator-rates.generated.ts" },
  { folder: "affiliate-products", typeName: "AffiliateProduct", exportName: "affiliateProducts", outFile: "affiliate-products.generated.ts" },
];

if (!existsSync(generatedDir)) mkdirSync(generatedDir, { recursive: true });

for (const entity of ENTITIES) {
  const entityDir = path.join(dataDir, entity.folder);
  if (!existsSync(entityDir)) {
    console.warn(`[generate-data] skipping "${entity.folder}" — src/data/${entity.folder} does not exist`);
    continue;
  }

  const files = readdirSync(entityDir)
    .filter((f) => f.endsWith(".json"))
    .sort();

  const importLines = files.map((f, i) => `import entry${i} from "../../data/${entity.folder}/${f}";`);
  const entryNames = files.map((_, i) => `entry${i}`).join(", ");

  // "as EntityType[]" is required, not stylistic: TypeScript always widens a
  // JSON import's string-literal fields to plain `string` (it never narrows
  // to a literal union like "kecil" | "menengah" | "besar"), so a bare
  // `: EntityType[]` annotation fails to type-check on every entity that has
  // a literal-union field, regardless of whether the JSON content is valid.
  const contents = `// AUTO-GENERATED by scripts/generate-data.mjs — do not edit by hand.
import type { ${entity.typeName} } from "@/lib/types";
${importLines.join("\n")}

export const ${entity.exportName} = [${entryNames}] as ${entity.typeName}[];
`;

  writeFileSync(path.join(generatedDir, entity.outFile), contents, "utf8");
  console.log(`[generate-data] ${entity.folder}: ${files.length} entr${files.length === 1 ? "y" : "ies"} -> ${entity.outFile}`);
}
